version: "3.0"

services:
  app:
    build: .
    ports:
    - 8080:8080
    environment:
      APP_MYSQL_URL: jdbc:mysql://mysql/cadastropessoas?createDatabaseIfNotExist=true
      APP_MYSQL_USERNAME: root
      APP_MYSQL_PASSWORD: root
    links:
      - mysql
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
