version: "3.0"

services:
  app:
    build: .
    ports:
    - 8080:8080
    environment:
      APP_MYSQL_URL: jdbc:mysql://mysql/cadastropessoas?createDatabaseIfNotExist=true
      APP_MYSQL_USERNAME: root
      APP_MYSQL_PASSWORD: root
      APP_GOOGLE_CLIENT_ID: 364019609391-l897u16hg9q7t5nhh5kn263rfjs3as4h.apps.googleusercontent.com
      APP_GOOGLE_CLIENT_SECRET: jFN_wGaXCtv1S6KjOnx2XzUC
    links:
      - mysql
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
