spring:
  datasource:
    url: ${APP_MYSQL_URL}
    username: ${APP_MYSQL_USERNAME}
    password: ${APP_MYSQL_PASSWORD}
  security:
    user:
      name: pessoa
      password: 123

app:
  source:
    code:
      url: https://github.com/william-balan/cadastro-pessoas
