spring:
  datasource:
    url: ${APP_MYSQL_URL}
    username: ${APP_MYSQL_USERNAME}
    password: ${APP_MYSQL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${APP_GOOGLE_CLIENT_ID}
            client-secret: ${APP_GOOGLE_CLIENT_SECRET}

app:
  source:
    code:
      url: https://github.com/william-balan/cadastro-pessoas
