spring:
  datasource:
    url: ${APP_MYSQL_URL}
    username: ${APP_MYSQL_USERNAME}
    password: ${APP_MYSQL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 364019609391-l897u16hg9q7t5nhh5kn263rfjs3as4h.apps.googleusercontent.com
            client-secret: jFN_wGaXCtv1S6KjOnx2XzUC


